name: zaracast
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cached_network_image: ^3.4.1
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  go_router: ^14.4.1
  http: ^1.1.0
  intl: ^0.19.0
  palette_generator: ^0.3.3+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true